### ISSUE TITLE
Kelvin needs to learn how to deal with branches!

### ISSUE THREAD

**Issue by kl1986** [KatieA88/CreditScorecard#6]

**Comment by kl1986** [comment]
Here are some basic commands that worked for me

'set up and checkout new branch
Git branch NAME-OF-BRANCH   (note that this must be one word but hyphens allowed)
Git checkout NAME-OF-BRANCH

'do coding then commit as usual
Git add -A
Git commit -m "YOUR CHOSEN MESSAGE"

'push this to your new branch - need to set up target first time
Git push --set-upstream origin NAME-OF-BRANCH

'now merge
Git checkout main
Git status
Git merge main

We will now need to go into the github page and create a pull request

**Comment by kl1986** [comment]
@KatieA88 may be worth us using this pull requests as a way of communicating what we've done.  I'm new to this so may be a quick chat on how this should work would be helpful?

**Comment by KatieA88** [comment]
@kl1986  Yes happy to chat through. Looks like youve got it though, those commands are right :) I need to check if github handles merges for notebooks or if we need to keep it as python files in VS code. Let me know when you've got some time and we can walk through how we could manage this

**Comment by KatieA88** [comment]
@kl1986  Also keep in mind that when you do git push, you can push into a branch or back into the master
